package content

import "errors"

var (
	ErrContentTypeRequired                   = errors.New("content: content type does not exist")
	ErrSlugRequired                          = errors.New("content: slug is required")
	ErrSlugInvalid                           = errors.New("content: slug contains invalid characters")
	ErrSlugExists                            = errors.New("content: slug already exists")
	ErrNoTranslations                        = errors.New("content: at least one translation is required")
	ErrDefaultLocaleRequired                 = errors.New("content: default locale translation is required")
	ErrDuplicateLocale                       = errors.New("content: duplicate locale provided")
	ErrUnknownLocale                         = errors.New("content: unknown locale")
	ErrContentSchemaInvalid                  = errors.New("content: schema validation failed")
	ErrContentSoftDeleteUnsupported          = errors.New("content: soft delete not supported")
	ErrContentIDRequired                     = errors.New("content: content id required")
	ErrContentMetadataInvalid                = errors.New("content: metadata invalid")
	ErrVersioningDisabled                    = errors.New("content: versioning feature disabled")
	ErrContentVersionRequired                = errors.New("content: version identifier required")
	ErrContentVersionConflict                = errors.New("content: base version mismatch")
	ErrContentVersionAlreadyPublished        = errors.New("content: version already published")
	ErrContentVersionRetentionExceeded       = errors.New("content: version retention limit reached")
	ErrSchedulingDisabled                    = errors.New("content: scheduling feature disabled")
	ErrScheduleWindowInvalid                 = errors.New("content: publish_at must be before unpublish_at")
	ErrScheduleTimestampInvalid              = errors.New("content: schedule timestamp is invalid")
	ErrContentTranslationsDisabled           = errors.New("content: translations feature disabled")
	ErrContentTranslationNotFound            = errors.New("content: translation not found")
	ErrContentSchemaMigrationRequired        = errors.New("content: schema migration required")
	ErrContentTranslationLookupUnsupported   = errors.New("content: translation lookup unsupported")
	ErrContentProjectionModeInvalid          = errors.New("content: projection translation mode is invalid")
	ErrContentProjectionUnsupported          = errors.New("content: projection is not supported")
	ErrContentProjectionRequiresTranslations = errors.New("content: projection requires translations")
	ErrEmbeddedBlocksResolverMissing         = errors.New("content: embedded blocks resolver not configured")

	ErrContentTypeNameRequired   = errors.New("content type: name is required")
	ErrContentTypeSchemaRequired = errors.New("content type: schema is required")
	ErrContentTypeSchemaInvalid  = errors.New("content type: schema is invalid")
	ErrContentTypeIDRequired     = errors.New("content type: id required")
	ErrContentTypeSlugInvalid    = errors.New("content type: slug contains invalid characters")
	ErrContentTypeSchemaVersion  = errors.New("content type: schema version invalid")
	ErrContentTypeSchemaBreaking = errors.New("content type: schema has breaking changes")
	ErrContentTypeStatusInvalid  = errors.New("content type: status invalid")
	ErrContentTypeStatusChange   = errors.New("content type: status transition invalid")
)
